############################# English ############################
[en]
languageName = "En"
title = "Pandion Digital Productions"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Support"
footer_menu_right = "Support"
footer_content = "The premiere production and design studio in the Pacific Northwest."
# copyright
copyright = "Copyright © 2021 Pandion LLC. All rights reserved."