[[main]]
name = "About Us"
url = ""
weight = 1

[[main]]
name = "Projects"
url = ""
weight = 2

[[main]]
name = "Merchandise"
url = ""
weight = 3

[[main]]
name = "Gear Rental"
url = "https://www.sharegrid.com/p/dNg35-gimr6OaaaKkSeqad"
weight = 4

[[main]]
name = "Stock"
url = ""
weight = 5

# footer menu left
[[footer_left]]
name = "About Us"
url = "#"

# footer menu right
[[footer_middle]]
name = "Privacy Policy"
url = "privacy-policy"

[[footer_middle]]
name = "Terms & Conditions"
url = "terms-conditions"